// <auto-generated />
using System;
using Logistica.Datos;
using Logistica.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistica.Migrations
{
    [DbContext(typeof(LogisticaDbContext))]
    partial class LogisticaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_pedido", new[] { "borrador", "confirmado", "en_ruta", "entregado", "fallido", "reprogramado", "devuelto", "cancelado" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistica.Datos.ParadaRepartidor", b =>
                {
                    b.Property<int>("Bultos")
                        .HasColumnType("integer")
                        .HasColumnName("bultos");

                    b.Property<string>("CalleNumero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calle_numero");

                    b.Property<string>("DestinatarioNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destinatario_nombre");

                    b.Property<string>("DestinatarioTelefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destinatario_telefono");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric")
                        .HasColumnName("lat");

                    b.Property<DateTimeOffset?>("LlegadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("llegada_en");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("numeric")
                        .HasColumnName("lng");

                    b.Property<string>("Localidad")
                        .HasColumnType("text")
                        .HasColumnName("localidad");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long>("ParadaId")
                        .HasColumnType("bigint")
                        .HasColumnName("parada_id");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<long>("RutaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ruta_id");

                    b.Property<DateTimeOffset?>("SalidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("salida_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.ToTable((string)null);

                    b.ToView("v_paradas_repartidor", (string)null);
                });

            modelBuilder.Entity("Logistica.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ColorOper")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("amarillo")
                        .HasColumnName("color_oper");

                    b.Property<string>("ColorPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("rojo")
                        .HasColumnName("color_pago");

                    b.Property<string>("ColorTrato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("amarillo")
                        .HasColumnName("color_trato");

                    b.Property<string>("Contacto")
                        .HasColumnType("text")
                        .HasColumnName("contacto");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Cuit")
                        .HasColumnType("text")
                        .HasColumnName("cuit");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("clientes", null, t =>
                        {
                            t.HasCheckConstraint("ck_clientes_color_oper", "color_oper in ('verde','amarillo','rojo')");

                            t.HasCheckConstraint("ck_clientes_color_pago", "color_pago in ('verde','amarillo','rojo')");

                            t.HasCheckConstraint("ck_clientes_color_trato", "color_trato in ('verde','amarillo','rojo')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.ClienteUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("clientes_usuarios", (string)null);
                });

            modelBuilder.Entity("Logistica.Entidades.EventoCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Nota")
                        .HasColumnType("text")
                        .HasColumnName("nota");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<Guid?>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_id");

                    b.Property<decimal?>("ValorNum")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_num");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("TipoId");

                    b.HasIndex("ClienteId", "OcurridoEn");

                    b.ToTable("eventos_cliente", (string)null);
                });

            modelBuilder.Entity("Logistica.Entidades.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cp")
                        .HasColumnType("text")
                        .HasColumnName("cp");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Partido")
                        .HasColumnType("text")
                        .HasColumnName("partido");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("integer")
                        .HasColumnName("zona_id");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.HasIndex("Nombre", "Partido")
                        .IsUnique();

                    b.ToTable("localidades", (string)null);
                });

            modelBuilder.Entity("Logistica.Entidades.ParadaPedido", b =>
                {
                    b.Property<long>("ParadaId")
                        .HasColumnType("bigint")
                        .HasColumnName("parada_id");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.HasKey("ParadaId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("parada_pedidos", (string)null);
                });

            modelBuilder.Entity("Logistica.Entidades.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Bultos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("bultos");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DescuentoRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento_ruta");

                    b.Property<string>("DestinatarioNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destinatario_nombre");

                    b.Property<string>("DestinatarioTelefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destinatario_telefono");

                    b.Property<long>("DestinoUbicacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("destino_ubicacion_id");

                    b.Property<EstadoPedido>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_pedido")
                        .HasDefaultValue(EstadoPedido.Borrador)
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("OrigenCarga")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("interno")
                        .HasColumnName("origen_carga");

                    b.Property<long>("OrigenUbicacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("origen_ubicacion_id");

                    b.Property<decimal>("Peajes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("peajes");

                    b.Property<long?>("PedidoOrigenId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_origen_id");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("peso_kg");

                    b.Property<decimal?>("PrecioBase")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_base");

                    b.Property<DateTimeOffset?>("PrecioCongeladoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("precio_congelado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("RecargoUrgencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("recargo_urgencia");

                    b.Property<string>("ReferenciaCliente")
                        .HasColumnType("text")
                        .HasColumnName("referencia_cliente");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("entrega")
                        .HasColumnName("tipo");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<bool>("Urgente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("urgente");

                    b.Property<decimal?>("ValorDeclarado")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_declarado");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("integer")
                        .HasColumnName("zona_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinoUbicacionId");

                    b.HasIndex("OrigenUbicacionId");

                    b.HasIndex("PedidoOrigenId");

                    b.HasIndex("ZonaId");

                    b.HasIndex("ClienteId", "FechaEntrega");

                    b.HasIndex("FechaEntrega", "Estado");

                    b.ToTable("pedidos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_bultos", "bultos > 0");

                            t.HasCheckConstraint("ck_pedidos_origen_carga", "origen_carga in ('interno','importado','portal','api')");

                            t.HasCheckConstraint("ck_pedidos_origen_coherente", "tipo = 'entrega' or pedido_origen_id is not null");

                            t.HasCheckConstraint("ck_pedidos_tipo", "tipo in ('entrega','retorno','reintento')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.PedidoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorTexto")
                        .HasColumnType("text")
                        .HasColumnName("actor_texto");

                    b.Property<string>("ActorTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_tipo");

                    b.Property<Guid?>("ActorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_usuario_id");

                    b.Property<EstadoPedido?>("EstadoAnterior")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado_anterior");

                    b.Property<EstadoPedido>("EstadoNuevo")
                        .HasColumnType("estado_pedido")
                        .HasColumnName("estado_nuevo");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorUsuarioId");

                    b.HasIndex("PedidoId", "OcurridoEn");

                    b.ToTable("pedido_eventos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_eventos_actor_identificado", "actor_tipo = 'sistema' or actor_usuario_id is not null");

                            t.HasCheckConstraint("ck_pedido_eventos_actor_tipo", "actor_tipo in ('sistema','usuario')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.PruebaEntrega", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capturada_en");

                    b.Property<int?>("DesvioMetros")
                        .HasColumnType("integer")
                        .HasColumnName("desvio_metros");

                    b.Property<string>("DeviceUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_uuid");

                    b.Property<string>("FotoPath")
                        .HasColumnType("text")
                        .HasColumnName("foto_path");

                    b.Property<bool>("IdentidadVerificada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("identidad_verificada");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("lng");

                    b.Property<string>("MotivoFallo")
                        .HasColumnType("text")
                        .HasColumnName("motivo_fallo");

                    b.Property<long?>("ParadaId")
                        .HasColumnType("bigint")
                        .HasColumnName("parada_id");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<string>("ReceptorNombre")
                        .HasColumnType("text")
                        .HasColumnName("receptor_nombre");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resultado");

                    b.Property<DateTimeOffset>("SincronizadaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sincronizada_en")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CapturadaEn");

                    b.HasIndex("ParadaId");

                    b.HasIndex("PedidoId", "DeviceUuid")
                        .IsUnique();

                    b.ToTable("pruebas_entrega", null, t =>
                        {
                            t.HasCheckConstraint("ck_pruebas_entrega_resultado", "resultado in ('entregado','fallido')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_usuario_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreadoPorIp")
                        .HasColumnType("text")
                        .HasColumnName("creado_por_ip");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid?>("ReemplazadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("reemplazado_por_id");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteUsuarioId");

                    b.HasIndex("ReemplazadoPorId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_actor_unico", "(usuario_id is not null and cliente_usuario_id is null) or (usuario_id is null and cliente_usuario_id is not null)");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.Ruta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CapacidadParadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("capacidad_paradas");

                    b.Property<DateTimeOffset?>("CerradaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_en");

                    b.Property<decimal?>("CombustibleMonto")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("combustible_monto");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("planificada")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("KmFinal")
                        .HasColumnType("integer")
                        .HasColumnName("km_final");

                    b.Property<int?>("KmInicial")
                        .HasColumnType("integer")
                        .HasColumnName("km_inicial");

                    b.Property<string>("NotasCierre")
                        .HasColumnType("text")
                        .HasColumnName("notas_cierre");

                    b.Property<long?>("OrigenUbicacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("origen_ubicacion_id");

                    b.Property<decimal?>("OtrosCostos")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("otros_costos");

                    b.Property<decimal?>("PagoRepartidor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("pago_repartidor");

                    b.Property<decimal?>("PeajesMonto")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("peajes_monto");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("repartidor_id");

                    b.Property<long?>("VehiculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("OrigenUbicacionId");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("rutas", null, t =>
                        {
                            t.HasCheckConstraint("ck_rutas_estado", "estado in ('planificada','en_curso','cerrada')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.RutaParada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Anclada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("anclada");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("LlegadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("llegada_en");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long>("RutaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ruta_id");

                    b.Property<DateTimeOffset?>("SalidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("salida_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<long>("UbicacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id");

                    b.HasIndex("RutaId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("ruta_paradas", null, t =>
                        {
                            t.HasCheckConstraint("ck_ruta_paradas_estado", "estado in ('pendiente','completada','fallida')");

                            t.HasCheckConstraint("ck_ruta_paradas_tipo", "tipo in ('retiro','entrega','deposito')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.Tarifa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("camioneta")
                        .HasColumnName("tipo_vehiculo");

                    b.Property<DateOnly>("VigenteDesde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("vigente_desde")
                        .HasDefaultValueSql("current_date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigente_hasta");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer")
                        .HasColumnName("zona_id");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.HasIndex("ClienteId", "ZonaId", "TipoVehiculo")
                        .HasFilter("vigente_hasta is null");

                    b.ToTable("tarifas", null, t =>
                        {
                            t.HasCheckConstraint("ck_tarifas_precio", "precio > 0");

                            t.HasCheckConstraint("ck_tarifas_tipo_vehiculo", "tipo_vehiculo in ('camioneta','moto')");

                            t.HasCheckConstraint("ck_tarifas_vigencia", "vigente_hasta is null or vigente_hasta >= vigente_desde");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.TipoEventoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tipos_evento_cliente", null, t =>
                        {
                            t.HasCheckConstraint("ck_tipos_evento_cliente_dimension", "dimension in ('pago','trato','operacion')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.Ubicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CalleNumero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calle_numero");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GeoConfianza")
                        .HasColumnType("text")
                        .HasColumnName("geo_confianza");

                    b.Property<DateTimeOffset?>("GeoFecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("geo_fecha");

                    b.Property<string>("GeoProveedor")
                        .HasColumnType("text")
                        .HasColumnName("geo_proveedor");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("lng");

                    b.Property<int?>("LocalidadId")
                        .HasColumnType("integer")
                        .HasColumnName("localidad_id");

                    b.Property<string>("NombreDeposito")
                        .HasColumnType("text")
                        .HasColumnName("nombre_deposito");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<bool>("Verificada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verificada");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.HasIndex("NombreDeposito")
                        .IsUnique()
                        .HasFilter("nombre_deposito is not null");

                    b.ToTable("ubicaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_ubicaciones_geo_confianza", "geo_confianza in ('alta','media','baja','fallida')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_rol", "rol in ('administracion','operacion','repartidor')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.Vehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int?>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<int>("CapacidadParadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("capacidad_paradas");

                    b.Property<decimal?>("CostoKm")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_km");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("KmActual")
                        .HasColumnType("integer")
                        .HasColumnName("km_actual");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patente");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("camioneta")
                        .HasColumnName("tipo");

                    b.Property<DateOnly?>("VenceSeguro")
                        .HasColumnType("date")
                        .HasColumnName("vence_seguro");

                    b.Property<DateOnly?>("VenceVtv")
                        .HasColumnType("date")
                        .HasColumnName("vence_vtv");

                    b.HasKey("Id");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("vehiculos", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehiculos_anio", "anio is null or anio between 1950 and 2100");

                            t.HasCheckConstraint("ck_vehiculos_capacidad", "capacidad_paradas > 0");

                            t.HasCheckConstraint("ck_vehiculos_tipo", "tipo in ('camioneta','moto')");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("codigo");

                    b.Property<int?>("KmDesde")
                        .HasColumnType("integer")
                        .HasColumnName("km_desde");

                    b.Property<int?>("KmHasta")
                        .HasColumnType("integer")
                        .HasColumnName("km_hasta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("zonas", null, t =>
                        {
                            t.HasCheckConstraint("ck_zonas_km_desde", "km_desde is null or km_desde >= 0");

                            t.HasCheckConstraint("ck_zonas_km_rango", "km_hasta is null or km_desde is null or km_hasta > km_desde");
                        });
                });

            modelBuilder.Entity("Logistica.Entidades.ClienteUsuario", b =>
                {
                    b.HasOne("Logistica.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Logistica.Entidades.EventoCliente", b =>
                {
                    b.HasOne("Logistica.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logistica.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.TipoEventoCliente", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");

                    b.Navigation("RegistradoPor");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Logistica.Entidades.Localidad", b =>
                {
                    b.HasOne("Logistica.Entidades.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Logistica.Entidades.ParadaPedido", b =>
                {
                    b.HasOne("Logistica.Entidades.RutaParada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logistica.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parada");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Logistica.Entidades.Pedido", b =>
                {
                    b.HasOne("Logistica.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logistica.Entidades.Ubicacion", "DestinoUbicacion")
                        .WithMany()
                        .HasForeignKey("DestinoUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logistica.Entidades.Ubicacion", "OrigenUbicacion")
                        .WithMany()
                        .HasForeignKey("OrigenUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logistica.Entidades.Pedido", "PedidoOrigen")
                        .WithMany()
                        .HasForeignKey("PedidoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("DestinoUbicacion");

                    b.Navigation("OrigenUbicacion");

                    b.Navigation("PedidoOrigen");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Logistica.Entidades.PedidoEvento", b =>
                {
                    b.HasOne("Logistica.Entidades.Usuario", "ActorUsuario")
                        .WithMany()
                        .HasForeignKey("ActorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUsuario");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Logistica.Entidades.PruebaEntrega", b =>
                {
                    b.HasOne("Logistica.Entidades.RutaParada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parada");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Logistica.Entidades.RefreshToken", b =>
                {
                    b.HasOne("Logistica.Entidades.ClienteUsuario", "ClienteUsuario")
                        .WithMany()
                        .HasForeignKey("ClienteUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Logistica.Entidades.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReemplazadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ClienteUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Logistica.Entidades.Ruta", b =>
                {
                    b.HasOne("Logistica.Entidades.Ubicacion", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenUbicacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.Usuario", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Origen");

                    b.Navigation("Repartidor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Logistica.Entidades.RutaParada", b =>
                {
                    b.HasOne("Logistica.Entidades.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logistica.Entidades.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ruta");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Logistica.Entidades.Tarifa", b =>
                {
                    b.HasOne("Logistica.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Logistica.Entidades.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Logistica.Entidades.Ubicacion", b =>
                {
                    b.HasOne("Logistica.Entidades.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Localidad");
                });
#pragma warning restore 612, 618
        }
    }
}
